server:
  port: ${PORT:9090}

info:
  name: dashboard-backend
  description: Dashboard backend service


# Liquibase
liquibase:
    change-log: classpath:/liquibase/liquibase.xml
    enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true

---

spring:
  profiles: mysql
# Datasource

  datasource:
    url: jdbc:mysql://mysql.c7tgrwaftmua.eu-central-1.rds.amazonaws.com:3306/smiletime?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    properties:
    jadira.usertype.autoRegisterUserTypes: true

---

spring:
    profiles: postgres
    datasource:
      url: jdbc:postgresql://localhost/dashboard
      username: root
      password: root
      driverClassName: org.postgresql.Driver
      maximumPoolSize: 100
      minimumIdle: 10
      connectionTestQuery: SELECT 1 FROM DUAL

    jpa:
      show-sql: false
      properties:
      jadira.usertype.autoRegisterUserTypes: true